### ISSUE TITLE
Change events not working properly

### ISSUE THREAD

**Issue by aommm** [BBWeb/derby-view#1]
When something on an underlying derby path changes, on which we have attached a view, it is not handled correctly.

One change on derby path can result in different things being emitted than last time. For us, one such change can result in:
- add events (if new keys are emitted which were not present last time)
- remove events (if old keys are NOT emitted this time)
- change events (if old keys are emitted this time, but pointing to different paths)

Idea how to accomplish this:
1. Get emits which were done last time (saved in 'ids' / 'idsSegments')
2. Get emits which are done right now (fake del/add which records them somehow)
3. Diff them
4. Emit add/remove events according to diff
5. Emit change events according to diff

Bulletpoint 5 is tricky. In some cases we need to stop our own events, and in some cases we need to stop derby's events (which are sent automatically through the refs we have created).

We also need to emit our own events in some places.

**Comment by cjblomqvist** [comment]
Fixed.
